language: ruby

before_script:
  - cd spec/dummy_app
  - bundle install
  # Piggyback of the Rails Admin CI rake task
  - bundle exec rake rails_admin:prepare_ci_env
  - bundle exec rake db:create db:migrate
  - cd ../../

bundler_args: --without development --jobs=3 --retry=3

cache: bundler

env:
  matrix:
    - CI_ORM=mongoid
    - CI_ORM=active_record CI_DB_ADAPTER=sqlite3
    - CI_ORM=active_record CI_DB_ADAPTER=mysql2
    - CI_ORM=active_record CI_DB_ADAPTER=postgresql CI_DB_USERNAME=postgres

rvm:
  - 2.4

services:
  - mongodb

